language: objective-c
matrix:
    include:
        - osx_image: xcode8.0
          env: SDK=macosx10.12 BUILD_OSX=1
        - osx_image: xcode8.0
          env: SDK=iphonesimulator10.0
        - osx_image: xcode8.0
          env: SDK=appletvsimulator10.0
        - osx_image: xcode7.3
          env: SDK=macosx10.11 BUILD_OSX=1
        - osx_image: xcode7.3
          env: SDK=iphonesimulator9.3
        - osx_image: xcode7.3
          env: SDK=appletvsimulator9.2
install: make bootstrap
script: make test
